# Generated by Django 4.2.9 on 2026-06-18 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stylist', '0004_collection_userprofile_last_limit_reset_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatmessage',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='chat/generated_outfits/'),
        ),
        migrations.AddField(
            model_name='chatmessage',
            name='metadata',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='gender',
            field=models.CharField(blank=True, choices=[('woman', 'Женщина'), ('man', 'Мужчина'), ('non_binary', 'Небинарный'), ('prefer_not_to_say', 'Предпочитаю не указывать')], max_length=32),
        ),
    ]
